kind = "mobile"
previewPath = "/"
title = "profeandres"
version = "1.0.0"
id = "artifacts/profeandres"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 20332

[services.development]
run = "pnpm --filter @workspace/profeandres run dev"
[services.production]
build = [ "pnpm", "--filter", "@workspace/profeandres", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/profeandres", "run", "serve" ]

[services.env]
PORT = "20332"
BASE_PATH = "/"
